creating new project
ordinarray/AndroidCourse65Apps pull request #1
Opened 2021-10-05 19:18 UTC by ordinarray

2021-10-06 16:04 UTC, goblinr requested changes

2021-10-06 16:04 UTC, goblinr commented on app/build.gradle
> +        applicationId "com.home.androidcourse65apps"
Нужно привязать `applicationId` к вашей почте. Т.е. если `home@gmail.com` - это ваша почта, то тогда это валидный `applicationId`, но я сомневаюсь, что это ваша почта

2021-10-06 16:04 UTC, goblinr commented on app/src/androidTest/java/com/home/androidcourse65apps/ExampleInstrumentedTest.kt
> +package com.home.androidcourse65apps
Соответственно, нужно будет поменять package name

2021-10-07 17:40 UTC, ordinarray commented on app/build.gradle
> +        applicationId "com.home.androidcourse65apps"
Исправлено

2021-10-07 17:40 UTC, ordinarray commented on app/src/androidTest/java/com/home/androidcourse65apps/ExampleInstrumentedTest.kt
> +package com.home.androidcourse65apps
package name изменен

2021-10-08 05:15 UTC, goblinr approved these changes

2021-10-08 05:15 UTC, merged